### ISSUE TITLE
Skip python coding style check when no python involved

### ISSUE THREAD

**Issue by ysun** [intel/lkvs#245]
It should pass python coding style check when the PR has no python code, but it is failed now.

![image](https://github.com/intel/lkvs/assets/1448148/380b0f5f-4f26-43ce-947e-924e17fedc38)

**Comment by xhao22** [comment]
Fixed in [#246](https://github.com/intel/lkvs/pull/246)

PR check result: https://github.com/intel/lkvs/actions/runs/9278660014/job/25530011914?pr=246

**Comment by ysun** [comment]
Thanks @xhao22  for the quick response!
