### ISSUE TITLE
amx tests can not be run with runtests.py

### ISSUE THREAD

**Issue by xhao22** [intel/lkvs#396]
[root@gnr-bkc BM]# ./runtests.py -f amx/ -t amx/tests
Warning: None
JOB ID     : 4c54cb8b0485c0f60c24d95372484b65f63765a9
JOB LOG    : /root/avocado/job-results/job-2024-09-05T03.44-4c54cb8/job.log
 (lkvs-test-1/42) tmul: STARTED
 (lkvs-test-1/42) tmul: ERROR: [Errno 13] Permission denied: 'tmul' (0.00 s)
 (lkvs-test-2/42) tmul: STARTED
 (lkvs-test-2/42) tmul: ERROR: [Errno 13] Permission denied: 'tmul' (0.00 s)
...

**Comment by hongyuni** [comment]
hi @xhao22 , can you help to check if amx/tmul/tmul is available in your environment?

**Comment by xhao22** [comment]
Thanks Hongyu, I'll have a try. 
But seems it's not same as others feature testing with command "./runtests.py -f feature -t feature/tests", is it possible make them unified?

**Comment by hongyuni** [comment]
runtests.py defined option "-f feature" as "Directory of a feature to run the tests", for amx, the current tests are pointed to directory of "amx/tmul", that's a bit confusing. I can revise it to simplify as directory "amx".
